import "./globals.css";
import { Kanit } from "next/font/google";
import logo from "../../public/logo.png";
const fontName = Kanit({
  weight: "400",
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "Hit Solution",
  description: "Generated by create next app",
};

import { Providers } from "./providers";
import NavBar from "./shared/NavBar";

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="light" suppressHydrationWarning={true}>
      <body
        suppressHydrationWarning={true}
        className={`${fontName.className} antialiased`}
      >
        <Providers>
          <NavBar />
          {children}
        </Providers>
      </body>
    </html>
  );
}
