import "./globals.css";
import { DM_Sans, Kanit, Lato, Plus_Jakarta_Sans } from "next/font/google";
import logo from "../../public/logo.png";
const fontName = Lato({
  weight: "400",
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "Hit Solution",
  description: "Generated by create next app",
};

import { Providers } from "./providers";
import NavBar from "./shared/NavBar";
import Loader from "./loader";

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="light">
      <body
        suppressHydrationWarning
        className={`${fontName.className} antialiased bg-[#F8FAFC]`}
      >
        <Providers suppressHydrationWarning>
          <NavBar />
          <Loader suppressHydrationWarning>{children}</Loader>
        </Providers>
      </body>
    </html>
  );
}
