import localFont from "next/font/local";
import "./globals.css";
import { Kanit, Open_Sans, Poppins } from "next/font/google";
import logo from "../../public/logo.png";
const fontName = Kanit({ subsets: ["latin"], weight: "400" });

export const metadata = {
  title: "Hit Solution",
  description: "Generated by create next app",
};

import { Providers } from "./providers";
import NavBar from "./shared/NavBar";


export default function RootLayout({ children }) {
  return (
    <html lang="en" className="light">
      <body className={`${fontName.className} antialiased`}>
        <Providers>
          <NavBar />
          {children}
        </Providers>
      </body>
    </html>
  );
}
