"use client";

import Image from "next/image";
import blog1 from "../../../../public/blogImg/blog1.png";
import blog2 from "../../../../public/blogImg/blog2.png";
import blog3 from "../../../../public/blogImg/blog3.png";
import logo from "../../../../public/logo.png";
import { useParams } from "next/navigation";
import { motion } from "framer-motion";
import Link from "next/link";
import ReusableBackground from "@/components/ReusableBackground";
import { useState } from "react";
import notFoundImg from "../../../../public/notfoundImg/Not-Found.webp";

const blogData = [
  {
    id: 1,
    title: "How to Build a Successful Data Science Team: 6 Key Steps to Follow",
    category: "Data Science Insights",
    imgUrl: blog1,
    desc: "Building a data science team requires a strategic approach to identify the right skills, tools, and workflows. Organizations must define clear objectives, align them with business goals, and ensure team members have expertise in data analytics, machine learning, and software engineering. A well-structured data science team fosters a culture of continuous learning, collaboration, and innovation. Companies should focus on hiring a diverse team with strong problem-solving abilities, analytical thinking, and domain-specific knowledge. Furthermore, investing in cloud-based data tools, big data platforms, and automated machine learning models enhances productivity. Effective data governance and security frameworks must be established to protect sensitive data while ensuring compliance with regulations. Lastly, continuous performance monitoring, mentorship programs, and skill enhancement training play a crucial role in maintaining an agile and high-performing data science team.",
    author: "HIT Solution Data Science Team",
    authorImg: logo,
    publishDate: "January 11, 2025",
  },
  {
    id: 2,
    title: "6 Best Practices for Building Scalable Software Applications",
    category: "Software Development",
    imgUrl: blog2,
    desc: "Developing scalable software requires a deep understanding of architecture, technology stack, and future growth needs. Scalability ensures that applications handle increasing user demands, evolving functionalities, and performance expectations. Best practices include adopting microservices architecture, utilizing cloud infrastructure, implementing caching strategies, and prioritizing database optimization. Companies must also embrace CI/CD pipelines for continuous testing and deployment, ensuring smooth application updates without downtime. Implementing robust API design and documentation allows seamless integrations with third-party services. Automated load testing helps simulate real-world scenarios, identifying potential bottlenecks before launch. Security must remain a top priority, incorporating authentication mechanisms, role-based access control, and encryption techniques. Lastly, user feedback should drive software improvements, ensuring applications remain adaptable and user-centric.",
    author: "HIT Solution Team",
    authorImg: logo,
    publishDate: "October 28, 2024",
  },
  {
    id: 3,
    title: "6 Essential Steps to Build a Successful IoT Ecosystem",
    category: "IoT Innovations",
    imgUrl: blog3,
    desc: "Building an IoT ecosystem involves more than just connecting devices; it requires careful planning, security measures, and seamless integration. The first step is selecting the right IoT hardware, including sensors, microcontrollers, and connectivity modules. Data security is critical, requiring encryption, secure authentication, and compliance with industry regulations. Cloud platforms play a pivotal role in storing and processing massive amounts of real-time data generated by IoT devices. Organizations must implement robust analytics solutions to extract meaningful insights and drive automation. Developing a scalable communication protocol such as MQTT or CoAP ensures reliable data transfer between devices. Lastly, organizations should focus on continuous monitoring, firmware updates, and predictive maintenance strategies to enhance efficiency and extend device lifespans.",
    author: "HIT Solution Team",
    authorImg: logo,
    publishDate: "October 28, 2024",
  },
  {
    id: 4,
    title: "Top Web Development Trends to Watch in 2025",
    category: "Web Development Trends",
    imgUrl: blog1, // Replace with the actual web development blog image
    desc: "Web development is evolving rapidly, with new trends emerging each year that redefine how websites and applications are built. In 2025, serverless computing is expected to gain momentum, enabling developers to focus on writing code while cloud providers handle infrastructure management. AI-driven web applications will enhance user experiences with personalized recommendations and automated interactions. WebAssembly (WASM) will enable near-native performance in web applications, making browsers more powerful than ever. Progressive Web Apps (PWAs) will continue to rise, offering offline capabilities and mobile-friendly experiences. The adoption of low-code/no-code platforms will accelerate, allowing businesses to develop applications without extensive coding knowledge. Finally, cybersecurity will remain a top priority, with advancements in blockchain-based authentication and secure API communication protocols ensuring enhanced web security.",
    author: "HIT Web Dev Insights Team",
    authorImg: logo,
    publishDate: "January 14, 2025",
  },
  {
    id: 5,
    title: "How Artificial Intelligence is Transforming Software Development",
    category: "AI-Driven Software Development",
    imgUrl: blog2,
    desc: "Artificial intelligence is no longer a futuristic concept; it’s revolutionizing software development today. AI-powered tools are enhancing productivity by automating repetitive tasks such as code generation, debugging, and software testing. AI-driven analytics enable developers to identify performance bottlenecks, security vulnerabilities, and optimization strategies in real time. The rise of generative AI models is changing how developers write and structure code, allowing for more efficient development workflows. Natural language processing (NLP) is enhancing human-computer interactions, enabling AI-assisted coding solutions like GitHub Copilot. AI also plays a crucial role in predictive software maintenance, analyzing historical data to prevent system failures before they occur. In the future, AI will further integrate with DevOps practices, accelerating continuous integration and deployment while ensuring enhanced software reliability.",
    author: "HIT Solution Team",
    authorImg: logo,
    publishDate: "October 28, 2024",
  },
];

const BlogDetail = () => {
  const [loading, setLoading] = useState(false);
  const params = useParams();
  const { id } = params;

  if (!id) {
    setLoading(true);
  }
  if (loading) {
    return <p>Loading.....</p>;
  }

  const blog = blogData?.find((item) => item.id === parseInt(id));

  if (!blog) {
    return (
      <div className="flex flex-col items-center justify-center min-h-[60vh] bg-teal-50 p-8">
        <Image
          src={notFoundImg}
          alt="Not Found"
          className="w-64 h-40 object-cover rounded-lg shadow-lg mb-6"
        />
        <h2 className="text-teal-600 text-4xl font-bold mb-2">Oops!</h2>
        <p className="text-gray-700 text-lg">
          The blog you're looking for doesn't exist.
        </p>
        <a
          href="/blogs"
          className="mt-6 bg-teal-600 text-white px-6 py-3 rounded-lg shadow-md hover:bg-teal-700 transition duration-300"
        >
          Go Back to Blogs
        </a>
      </div>
    );
  }

  return (
    <ReusableBackground>
      <div className="md:container mx-auto px-6 py-12">
        {/* Blog Image with Animation */}
        <motion.div
          initial={{ opacity: 0, y: -50 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6, ease: "easeOut" }}
          className="relative w-full md:h-[500px] h-[250px] overflow-hidden"
        >
          <Image
            className="w-full h-full px-0 mx-0 object-cover rounded-lg shadow-lg"
            src={blog?.imgUrl}
            alt={blog?.title}
            width={1200}
            height={600}
            quality={100}
          />
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            transition={{ duration: 0.8, delay: 0.3 }}
            className="absolute bottom-0 left-0 bg-gradient-to-t from-gray-900 to-transparent w-full p-6"
          >
            <h1 className="text-teal-300 text-lg font-semibold">
              {blog?.category}
            </h1>
          </motion.div>
        </motion.div>

        {/* Blog Content */}
        <div className="max-w-4xl mx-auto mt-10">
          {/* Blog Title */}
          <motion.h1
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6, delay: 0.3 }}
            className="xl:text-5xl lg:text-4xl md:text-3xl text-2xl font-extrabold text-gray-900 leading-tight"
          >
            {blog?.title}
          </motion.h1>

          {/* Author & Publish Date */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6, delay: 0.4 }}
            className="flex items-center gap-4 mt-6"
          >
            <Image
              className="rounded-full border-2 border-teal-400"
              src={blog?.authorImg}
              alt={blog?.author}
              width={60}
              height={60}
              quality={100}
            />
            <div>
              <h2 className="font-semibold text-gray-800 text-lg">
                {blog?.author}
              </h2>
              <p className="text-gray-500">{blog?.publishDate}</p>
            </div>
          </motion.div>

          {/* Blog Description */}
          <motion.p
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6, delay: 0.5 }}
            className="text-gray-700 md:text-lg text-base mt-6  border-l-4 border-teal-500 pl-5"
          >
            {blog?.desc}
          </motion.p>

          {/* Animated Divider */}
          <motion.div
            initial={{ scaleX: 0 }}
            animate={{ scaleX: 1 }}
            transition={{ duration: 0.8, delay: 0.6, ease: "easeOut" }}
            className="mt-10 border-t-2 border-gray-300 w-full origin-left"
          ></motion.div>

          {/* Call-to-Action (Optional) */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6, delay: 0.7 }}
            className="mt-10"
          >
            <Link href={"/blogs"}>
              <motion.button
                whileHover={{ scale: 1.05 }}
                whileTap={{ scale: 0.95 }}
                className="bg-teal-600 text-white px-6 py-3 rounded-lg shadow-md hover:bg-teal-700 transition"
              >
                Read More Blogs
              </motion.button>
            </Link>
          </motion.div>
        </div>
      </div>
    </ReusableBackground>
  );
};

export default BlogDetail;
